import React from "react";

function head() {
	return (
		<div>
			<title>Arjun Silwal</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
		</div>
	);
}

export default head;
